### ISSUE TITLE
Frete mais caro ao selecionar "entregar no mesmo endereço"

### ISSUE THREAD

**Issue by fredpiuma** [FrenetGatewaydeFretes/frenet-magento#1]
Quando passamos do passo 1 do checkout, endereço de cobrança, diretamente pro passo 3, forma de entrega, ele transmite pra Frenet o valor do campo ShipmentInvoiceValue em dobro. Isso faz o cálculo vir mais caro.

Fiz um vídeo (de 2 minutos) mostrando como o erro ocorre:

[https://www.youtube.com/watch?v=Glec-vixsCA](https://www.youtube.com/watch?v=Glec-vixsCA)

Agradeço muito se puderem me dar uma luz de como resolver.

**Comment by fredpiuma** [comment]
Atualizei a versão do Magento e o problema sumiu. Deve ter sido um problema do Magento então.

**Comment by fredpiuma** [comment]
Pessoal, quando falei ali que resolveu, na verdade não resolveu, inclusive detectei mais um site com o mesmo problema.

Fiz um novo vídeo mostrando que nas últimas 4 versões do Magento 1.X o erro está presente.

[https://www.youtube.com/watch?v=XIIpQf8mXhc](https://www.youtube.com/watch?v=XIIpQf8mXhc)

Depois que fiz o vídeo tentei atualizar o módulo de vocês e até usar uma versão mais antiga e o erro continua.

**Comment by fredpiuma** [comment]
Consegui contornar o problema.

Pelo tempo sem resposta, desde que postei o problema, acredito que o módulo tenha sido descontinuado, correto?

Caso haja interesse na solução, chama no WhatsApp [(27) 99690-3465](https://wa.me/5527996903465)

**Comment by tiagosampaio** [comment]
@fredpiumee muito obrigado pelo seu feedback.

Poderia, por favor, descrever qual foi a solução que você encontrou?
