### ISSUE TITLE
Não calcula o frete

### ISSUE THREAD

**Issue by davirs** [FrenetGatewaydeFretes/frenet-magento#2]
Olá, eu instalei o módulo, configurei o token conforme instruções e demais campos do módulo.
Não retorna calculo nenhum. Poderia me ajudar com o log?

`[2020-07-15 23:40:23] frenet_log.DEBUG: {"request":{"json":{"SellerCEP":"24.716-453","RecipientCEP":"88317-200","RecipientCountry":"BR","ShipmentInvoiceValue":41.17,"ShippingItemArray":[{"SKU":"0300318IC-gg","Weight":0.15,"Length":16,"Height":2,"Width":11,"Quantity":1,"Category":"","isFragile":false}]},"headers":[]},"result":{"ShippingSevicesArray":[{"ServiceCode":"04162","ServiceDescription":"SEDEX","Carrier":"Correios","CarrierCode":"COR","Msg":"","Error":true,"ResponseTime":"2048.8534","AllowBuyLabel":false},{"ServiceCode":"04669","ServiceDescription":"PAC","Carrier":"Correios","CarrierCode":"COR","Msg":"","Error":true,"ResponseTime":"2002.1429","AllowBuyLabel":false}],"Timeout":0}} [] []`

**Comment by tiagosampaio** [comment]
@davirs aparentemente não existe problema com o módulo em si, pois está existindo o retorno corretamente, mas se repararmos existe um campo `"Error":true` o que faz com que os métodos não sejam renderizados no front.

Sugiro entrar em contato diretamente com o suporte da Frenet para obter ajuda com essa questão.

Abraços,

-Tiago
