### ISSUE TITLE
Peso de embalagem

### ISSUE THREAD

**Issue by wdarking** [FrenetGatewaydeFretes/frenet-magento#3]
Olá @tiagosampaio 

Existe alguma opção para que eu possa definir um peso de embalagem para o pacote de entrega?

Por exemplo: um pedido com 2 produtos deu 2kg. O módulo fazer um json com 2 objects no `ShippingItemArray`, cada um com 1kg. Nós usamos uma embalagem de 0.250kg ou 250g.

Teria alguma opção no módulo para incluir estes 250g de embalagem? Se não houver, qual classe eu poderia estender para aplicar esta correção?

**Comment by tiagosampaio** [comment]
Olá @wdarking, tudo bem?

Não existe esta opção atualmente. Você pode adicionar este peso no próprio produto.

Na realidade, eu gostaria de entender melhor o motivo desta necessidade.

Abraço.

Tiago

**Comment by wdarking** [comment]
Tudo bom @tiagosampaio !

No nosso caso, nós não usamos o peso da embalagem direto no produto. Eu até poderia definir um valor arbitrário de embalagem por produto, porém a cotação ficaria discrepante dependendo da quantidade de produtos colocada no carrinho.

Por exemplo: Cliente coloca 10 itens no carrinho. Supomos um peso de 0.1kg pra cada item, ou seja, peso total 1kg. A embalagem que eu vou utilizar tem 0.250kg. Eu poderia arbitrariamente incrementar 0.025kg no peso de cada produto pra compensar a embalagem. Ou seja, agora cada item tem 0.125kg, que multiplicados por 10 da 1.250kg, eu tenho o peso da embalagem e está ok. Porém, se o cliente colocar apenas 5 itens no carrinho, o peso que deveria ser da embalagem cai para 0.125kg, porém continuamos usando a embalagem de 0.250kg para um pedido de 5 itens.

Em nosso uso de caso, seria mais interessante ratear o peso da embalagem nos produtos de `ShippingItemArray`. Assim não aconteceria o problema descrito acima.

Ex. Cliente coloca 5 itens no carrinho. Supomos um peso de 0.1kg pra cada item, peso total 0.5kg. O sistema rateia o peso da embalagem entre esses 5 itens, ou seja, incrementa o peso do item em 0.050kg. Se fossem 10 itens no carrinho, incrementaria o peso em 0.025kg.

Sobre a necessidade, é algo mais especifico pra produtos com um ticket mais baixo, como livros e papéis por exemplo, onde o frete geralmente é mais caro que o próprio produto, e tem que ser calculado mais assertivamente pra evitar possíveis cotações discrepantes para o cliente e para o lojista, que acaba pagando a diferença.

Mas realmente era só uma dúvida. Eu vou estudar um pouco melhor o código aqui e ver onde seria o local ideal pra colocar este rateio de peso.

**Comment by tiagosampaio** [comment]
@wdarking entendi sua necessidade.

A classe que vai te ajudar é esta, provavelmente:

https://github.com/FrenetGatewaydeFretes/frenet-magento2/blob/master/Model/Catalog/Product/DimensionsExtractor.php#L91

Abraços.
