### ISSUE TITLE
Cotações diferentes.

### ISSUE THREAD

**Issue by romereza** [FrenetGatewaydeFretes/frenet-magento#6]
Olá,

Estou com o modulo instalado em nossa loja, www.irmaoshaluli.com.br, e percebemos que a cotação do frete está diferente no carrinho de compras e ao finalizar o pedido.

**Comment by rafaelmancini** [comment]
Olá, por favor envie os dados da divergência em nosso email de suporte (suporte@frenet.com.br). Nossa equipe irá localizar os logs de cotação e ajudá-lo.
Obrigado

**Comment by romereza** [comment]
Olá @rafaelmancini tudo bom?

Eu fiz o contato com eles através do chat, ele me retornaram que não prestava suporte ao módulo :(

Dei uma olhada no log das requisições e o problema é que nas requisições na tele de finalizar o pedido o módulo tá dobrando a quantidade de itens que tem no carrinho

**Comment by rafaelmancini** [comment]
Pode ter ocorrido um mau entendido pois a Frenet presta suporte ao módulo sim. Então por gentileza envie novamente essa informação para o suporte.

**Comment by romereza** [comment]
Acabei de enviar, obrigado.
